# Generated by Django 3.2.11 on 2022-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=256, verbose_name='Задание')),
                ('amount', models.PositiveIntegerField()),
                ('done', models.CharField(choices=[('0', 'Сделано'), ('1', 'Не сделано')], max_length=1)),
            ],
        ),
    ]
