# Generated by Django 3.2 on 2022-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'Сделано'), ('1', 'Не сделано')], default='Не сделано', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.PositiveIntegerField(),
        ),
    ]
